# Generated by Django 5.0.7 on 2024-07-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0002_alter_fad_decade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fad',
            name='description',
            field=models.TextField(),
        ),
    ]
